-- MySQL Script generated by MySQL Workbench
-- Wed Aug 21 21:13:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `idPatient` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `age` INT(4) NULL,
  `gender` ENUM('Femme', 'Homme') NULL,
  `Location` VARCHAR(45) NULL,
  `Email_Address` VARCHAR(45) NULL,
  `Mobile_number` VARCHAR(45) NULL,
  `Groupage` ENUM('O+', 'O-', 'AB+', 'AB-', 'A+', 'A-', 'B+', 'B-') NULL,
  PRIMARY KEY (`idPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test_Category` (
  `idTest Category` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTest Category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Type` ENUM('Médecin', 'LAborantin', 'réceptionniste') NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test` (
  `idTest` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Unit` VARCHAR(45) NULL,
  `Default_value` VARCHAR(45) NULL,
  `Cost` VARCHAR(45) NULL,
  `Normal_ range` VARCHAR(45) NULL,
  `Lower_range` VARCHAR(45) NULL,
  `Upper_range` VARCHAR(45) NULL,
  `Notes` VARCHAR(45) NULL,
  `Test_Category_idTest_Category` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NULL,
  PRIMARY KEY (`idTest`),
  INDEX `fk_Test_Test Category1_idx` (`Test_Category_idTest_Category` ASC),
  INDEX `fk_Test_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Test_Test Category1`
    FOREIGN KEY (`Test_Category_idTest_Category`)
    REFERENCES `mydb`.`Test_Category` (`idTest Category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test_Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test_Report` (
  `idTest Report` INT NOT NULL,
  `Date` DATE NULL,
  `received_date` DATE NULL,
  `Medecin_idMedecin` INT NULL,
  `Test_idTest` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NULL,
  `Patient_idPatient` INT NOT NULL,
  PRIMARY KEY (`idTest Report`, `Medecin_idMedecin`),
  INDEX `fk_Test Report_Test1_idx` (`Test_idTest` ASC),
  INDEX `fk_Test Report_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Test Report_Patient1_idx` (`Patient_idPatient` ASC),
  CONSTRAINT `fk_Test Report_Test1`
    FOREIGN KEY (`Test_idTest`)
    REFERENCES `mydb`.`Test` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test Report_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test Report_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `mydb`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facture` (
  `idFacture` INT NOT NULL,
  `Date` DATE NULL,
  `Total` DECIMAL NULL,
  `Patient_idPatient` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NULL,
  PRIMARY KEY (`idFacture`),
  INDEX `fk_Facture_Patient1_idx` (`Patient_idPatient` ASC),
  INDEX `fk_Facture_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Facture_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `mydb`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facture_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
